version: '3.8'
services:
  frontend:
    container_name: 'service-1'
    image: twjho/service-1_api
    build: ./service-1
    environment: 
      DATABASE_URI: sqlite:///data.db
    ports:
    - published: 5000
      target: 5000
  backend-country:
    container_name: 'service-2_api'
    image: twjho/service-2_api
    build: ./service-2   
  backend-numbers:
    container_name: 'service-3_api'
    image: twjho/service-3_api
    build: ./service-3      
  backend:
    container_name: 'backend-api'
    image: twjho/service-4_api
    build: ./service-4