version: '3.3'
services: 
    server:
        container_name: project_server 
        image: tomholmes98/project_server
        build: ./server
        environment:
            DATABASE_URI: sqlite:///flask.db
        ports:
        - published: 5000
          target: 5000
    server-2:
        container_name: project_service_2 
        image: tomholmes98/project_service_2 
        build: ./service-2 
    server-3:
        container_name: project_service_3 
        image: tomholmes98/project_service_3 
        build: ./service-3
    server-4:
        container_name: project_service_4
        image: tomholmes98/project_service_4
        build: ./service-4 