version: '3.3'
services: 
    server:
        container_name: project_server 
        image: tomholmes98/project_server
        build: ./server
        environment:
            DATABASE_URI: ${DATABASE_URI}
        ports:
        - published: 5000
          target: 5000
    service_2:
        container_name: project_server_2 
        image: tomholmes98/project_service_2 
        build: ./service-2
    service_3:
        container_name: project_server_3 
        image: tomholmes98/project_service_3 
        build: ./service-3
    service_4:
        container_name: project_server_4
        image: tomholmes98/project_service_4
        build: ./service-4 