- hosts: 
  - manager
  - worker
  become: true
  roles:
  - install-docker

- hosts: manager
  become: true
  roles:
  - docker-manager

- hosts: worker
  become: true
  roles:
  - docker-worker

- hosts: manager
  become: true
  tasks:
  - name: Copy docker-compose
    copy:
      src: docker-compose.yaml
      dest: docker-compose.yaml
