---
# tasks file for swarm-worker
- name: "Add worker to swarm"
  docker_swarm:
    state: join
    advertise_addr: docker-worker
    join_token: "{{ hostvars['docker-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker']}}"
    remote_addrs: [ 'docker-manager:2377' ]
